-- A executer une seule fois dans Supabase > SQL Editor.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  bar_name text not null,
  menu jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.profiles add column if not exists menu jsonb not null default '[]'::jsonb;

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  bar_id uuid not null references public.profiles(id) on delete cascade,
  label text not null,
  source text not null default 'registre',
  status text not null default 'nouvelle',
  paid boolean not null default false,
  items jsonb not null default '[]'::jsonb,
  total integer not null default 0 check (total >= 0),
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.orders enable row level security;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$ begin
  insert into public.profiles (id, bar_name, menu)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'bar_name', split_part(new.email, '@', 1)), '[]'::jsonb);
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.ensure_my_profile(profile_bar_name text, profile_menu jsonb)
returns public.profiles
language plpgsql
security definer
set search_path = public
as $$
declare result public.profiles;
begin
  if auth.uid() is null then
    raise exception 'Utilisateur non authentifie';
  end if;
  insert into public.profiles (id, bar_name, menu)
  values (auth.uid(), profile_bar_name, profile_menu)
  on conflict (id) do update set bar_name = excluded.bar_name
  returning * into result;
  return result;
end;
$$;
grant execute on function public.ensure_my_profile(text, jsonb) to authenticated;

drop policy if exists "profile own read" on public.profiles;
create policy "profile own read" on public.profiles for select using (id = auth.uid());
drop policy if exists "profile own insert" on public.profiles;
create policy "profile own insert" on public.profiles for insert with check (id = auth.uid());
drop policy if exists "profile own update" on public.profiles;
create policy "profile own update" on public.profiles for update using (id = auth.uid()) with check (id = auth.uid());
drop policy if exists "orders own read" on public.orders;
create policy "orders own read" on public.orders for select using (bar_id = auth.uid());
drop policy if exists "orders own insert" on public.orders;
create policy "orders own insert" on public.orders for insert with check (bar_id = auth.uid());
drop policy if exists "orders own update" on public.orders;
create policy "orders own update" on public.orders for update using (bar_id = auth.uid()) with check (bar_id = auth.uid());
drop policy if exists "orders own delete" on public.orders;
create policy "orders own delete" on public.orders for delete using (bar_id = auth.uid());
